name: wasmin
description: A programming language that is a thin layer over pure WebAssembly (WASM).
version: 0.0.0
homepage: https://github.com/renatoathaydes/wasmin
author: Renato Athaydes <renatoathaydes@hotmail.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  args: ^1.5.2
  collection: ^1.14.12

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.9.4
